[project]
name = "wa-gov-au-harvest-consultations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "elasticsearch>=8.17.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.3",
    "sqlmesh[github,mysql,web]>=0.140.1",
]
