name: SQLMesh Hourly
run-name: ðŸš€ SQLMesh Hourly ðŸš€
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  sqlmesh:
    name: SQLMesh Actions Workflow
    runs-on: training
    container:
      # Runner docker image
      image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    steps:
      - uses: actions/checkout@v4
      - name: Install SQLMesh + Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: Build and deploy sqlmesh prod env
        env:
          SECRETS_YAML: ${{ secrets.SECRETS_YAML }}
        run: sqlmesh plan --auto-apply --run --verbose
        shell: bash